//29
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.3.0.29")]
[assembly: AssemblyVersion("1.3.0.0")]
[assembly: AssemblyInformationalVersion("1.3.0")]
[assembly: KSPAssembly("ExceptionDetector", 1,3,0)]

namespace ExceptionDetector
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 3;
		public const int patch = 0;
		public const int build = 0;
		public const string Number = "1.3.0.0";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
		public const string SText = Number;
#endif
	}
}